name: Container Build
inputs:
  ecr-repository-uri:
    description: 'ECR Repository'
    required: true
  dockerfile-path:
    description: 'Dockerfile Path'
    required: true
outputs:
  container-image:
    value: ${{ steps.meta.outputs.tag }}
runs:
  using: 'composite'
  steps:
    - uses: aws-actions/amazon-ecr-login@v2
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: type=sha.format=long
    - uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ inputs.dockerfile-path }}
        tags: ${{ steps.meta.outputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}