name: Container Deploy
inputs:
  ecs-cluster:
    required: true
  ecs-service:
    required: true
  task-definition:
    required: true
  container-name:
    required: true
  container-image:
    required: true
runs:
  using: composite
  steps:
    - run: |
        aws ecs describe-task-definition --task-definition "${{ TASK_DEFINITION }}" \
          --query taskDefinition --output json > "${RUNNER_TEMP}/task-def.json"
      env:
        TASK_DEFINITION: ${{ inputs.task-definition }}
      shell: bash
    - uses: aws-actions/amazon-ecs-render-task-definition@v1
      id: render
      with:
        task-definition: ${{ runner.temp }}/task-def.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.container-image }}
    - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ inputs.ecs-cluster }}
        service: ${{ inputs.ecs-service }}
        task-definition: ${{ steps.render.outputs.task-definition }}